config/routes.rb
Rails.application.routes.draw do


  get 'roles/new'

  get 'roles/create'

  get 'roles/destroy'

  get 'roles/update'

  get 'assignments/new'

  get 'assignments/create'

  get 'assignments/destroy'

  get 'assignments/update'

  post '/signatures/new', to: 'signatures#sign'

  post '/form/finalize' => 'forms#finalize', :as => :finalize_form
  root to: "home#show"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :forms
  resources :form_types
  resources :roles
  resources :assignments
  resources :signatures

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show

    if !(Role.where(:name => 'admin').present?)
      Role.create(:name => 'admin')
    end

    if !(Role.where(:name => 'Undergrad Committee').present?)
      Role.create(:name => 'Undergrad Committee')
    end

    if !(Role.where(:name => 'Grad Committee').present?)
      Role.create(:name => 'Grad Committee')
    end

    #If the user's ID is present in the system(whatever it might be), check if
    # an assignment hasn't already been created. If not, assign("hardcode") the user
    # to the admin role.
    if (User.where(id: User.where(email: "cltalmad@go.olemiss.edu")).present?)
      user = User.where(:email => "cltalmad@go.olemiss.edu").first
      admin = Role.where(:name => 'admin').first
      if !(Assignment.find_by(id: user.id).present?)
        Assignment.create(:user_id => user.id, :role_id => admin.id)
      end
    end

    if (User.where(id: User.where(email: "jmricha4@go.olemiss.edu")).present?)
      user = User.where(:email => "jmricha4@go.olemiss.edu").first
      admin = Role.where(:name => 'admin').first
      if !(Assignment.find_by(id: user.id).present?)
        Assignment.create(:user_id => user.id, :role_id => admin.id)
      end
    end
    # Right now, this is where I'm hardcoding the Grad/Undergrad group..
    # We should put this in a control panel so that the admin can edit roles.
    if (User.where(id: User.where(email: "talmadge12@gmail.com")).present?)
      user = User.where(:email => "talmadge12@gmail.com").first
      admin = Role.where(:name => 'Undergrad Committee').first
      if !(Assignment.find_by(id: user.id).present?)
        Assignment.create(:user_id => user.id, :role_id => admin.id)
      end
    end

    if (User.where(id: User.where(email: "clt@olemiss.edu")).present?)
      user = User.where(:email => "clt@olemiss.edu").first
      admin = Role.where(:name => 'Grad Committee').first
      if !(Assignment.find_by(id: user.id).present?)
        Assignment.create(:user_id => user.id, :role_id => admin.id)
      end
    end


  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/control.html.erb
<% if !(current_user.role? :admin)

    redirect_to root_path
  end
  %>
<h3> Here you can: </h3>

<!--<%= link_to "New Role", new_role_path, class: "btn btn-primary"%><br><br>-->
<%= link_to "Assign User To Role", new_assignment_path, class: "btn btn-primary"%><br><br>
<!--<button type="button" class="btn btn-primary">Define workflow behavior</button><br><br>-->

app/views/home/show.html.erb
  <div class="billboard">
    <div align = center><%= image_tag("brevard.png", :alt => "School of Engineering Logo") %></div>
    <h1 align = center>Workflow App Homepage</h1>

    <!-- Log in button for the home page. The idea behind having a redundant button in place is so that when a user arrives, "sign in" will be the first
    thing that jumps out at them -->
    <div>
      <% if current_user %>
        <p align = center>
          <strong>
            Successfully signed in.
          </strong>
        </p>
      <% else %>
        <div align = center><%= link_to "Sign in with Google", "/auth/google_oauth2", class: "btn btn-primary btn-wide-1", id: "sign_in" %></div>
        <p align = center>
          <strong>
            Not logged in. Please sign in to continue.
          </strong>
        </p>
  </div>

  <% end %>


  <h1></h1>
  <%  if (User.find_by(email: "")) %>
    <h1> Found user </h1>
  <% end %>
</div>