config/routes.rb
Rails.application.routes.draw do


  get 'roles/new'

  get 'roles/create'

  get 'roles/destroy'

  get 'roles/update'

  get 'assignments/new'

  get 'assignments/create'

  get 'assignments/destroy'

  get 'assignments/update'

  post '/signatures/new', to: 'signatures#sign'

  post '/form/finalize' => 'forms#finalize', :as => :finalize_form
  root to: "home#show"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :forms
  resources :form_types
  resources :roles
  resources :assignments
  resources :signatures

end

app/controllers/form_types_controller.rb
class FormTypesController < ApplicationController

  before_action :require_login, :require_admin

  def index

    @form_types = FormType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @form_types}
    end
  end

  def show


    @form_type = FormType.find(params[:id])

    respond_to do |format|
      format.html
      format.json { render json: @form_type }
    end
  end

  def new
    @form_type = FormType.new

    respond_to do |format|
      format.html #new.html.erb
      format.json { render json: @form_types }
    end
  end

  def edit
    @form_type = FormType.find(params[:id])
  end

  def create
    @form_type = FormType.new(form_type_params)

    respond_to do |format|
      if @form_type.save
        format.html { redirect_to @form_type, notice: 'Form template was successfully created.' }
        format.json { render json: @form_type, status: :created, location: @form_type }
      else
        format.html { render action: "new" }
        format.json { render json: @form_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @form_type = FormType.find(params[:id])

    respond_to do |format|
      if @form_type.update_attributes(form_type_params)
        format.html { redirect_to @form_type, notice: 'Form type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @form_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @form_type = FormType.find(params[:id])
    @form_type.destroy

    respond_to do |format|
      format.html { redirect_to form_types_url }
      format.json { head :no_content }
    end
  end

  private
  def form_type_params
    params.require(:form_type).permit(:name, :id, fields_attributes: [:name, :id, :fields_attributes, :field_type, :required, :_destroy, :destroy, :remove])
  end

  def require_login
    unless !current_user.nil?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path # halts request cycle
    end
  end

  def require_admin
    unless current_user.role? :admin
      redirect_to root_path
    end
  end
end

app/helpers/form_types_helper.rb
module FormTypesHelper
end

app/views/form_types/_field_fields.html.erb
<fieldset class="fieldset">
  <%= f.select :field_type, %w[text_field check_box body] %>
  <%= f.text_field :name, placeholder: "field_name" %>
  <%= f.check_box :required %> <%= f.label :required %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/form_types/_form.html.erb
<%= form_for @form_type do |f| %>
  <% if @form_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form_type.errors.count, "error") %> prohibited this form_type from being saved:</h2>
      <ul>
      <% @form_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class= "sidebarFields">
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name %>
      </div>

      <%= f.fields_for :fields do |builder| %>
        <%= render 'field_fields', f: builder %>
      <% end %>
      <%= link_to_add_fields "Add Field", f, :fields %>

      <div class="actions">
        <%= f.submit "Done"%>
      </div>
    </div>
<% end %>

app/views/form_types/_form_fields.html.erb
<fieldset>
  <%= f.select :field_type, %w[text_field check_box] %>
  <%= f.text_field :name, placeholder: "field_name" %>
  <%= f.check_box :required %> <%= f.label :required %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/form_types/edit.html.erb
  <div class="sidebarEdit">
    <h1 class="editHead">Form Editor</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @form_type %> |
    <%= link_to 'Back', form_types_path %>
  </div>

  <div class="dropsite">

  </div>

app/views/form_types/index.html.erb
<% if current_user.nil? %>

  <h1> Not logged in. </h1>
<% end %>

<% if !current_user.role? :admin %>
  <h1> You do not have permission to view this page. </h1>
<% end%>

<!-- If there is a current user, and they are an admin,
     then render the form template index as normal. -->
<% if !current_user.nil? %>
  <% if current_user.role? :admin %>
<div class="sidebarEdit">
  <h1 class="editHead">Available Forms </h1>

    <table>
    <% @form_types.each do |form_type| %>
      <tr>
        <td class = "form_type"><%= form_type.name%></td>
        <td><%= link_to 'Show', form_type, class: 'avibuttons' %></td>
        <td><%= link_to 'Edit', edit_form_type_path(form_type), class: 'avibuttons' %></td>
        <td><%= link_to 'Destroy', form_type, method: :delete, data: { confirm: 'Are you sure?' }, class: 'avibuttons' %></td>
      </tr>
    <% end %>
    </table>
    <br />
    <%= link_to 'Create a new form...', new_form_type_path, class: 'newform'%>
  </div>

  <% end %>
<% end %>

app/views/form_types/new.html.erb
<div class="sidebarEdit">
  <% if current_user.nil? %>
    <h1> You must be logged in to view this page. </h1>
  <% end %>

  <h1>New form:</h1>

  <%= render 'form' %>

  <%= link_to 'Back', form_types_path %>
</div>

app/views/form_types/show.html.erb
<div class="sidebarEdit">
  <% if current_user.nil? %>
    <h1> You must be logged in to view this page. </h1>
  <% end %>




  <p id="notice"><%= notice %></p>

  <p>
    <b>Name:</b>
    <%= @form_type.name %>
  </p>


  <%= link_to 'Edit', edit_form_type_path(@form_type) %> |
  <%= link_to 'Back', form_types_path %>

</div>