config/routes.rb
Rails.application.routes.draw do


  get 'roles/new'

  get 'roles/create'

  get 'roles/destroy'

  get 'roles/update'

  get 'assignments/new'

  get 'assignments/create'

  get 'assignments/destroy'

  get 'assignments/update'

  post '/signatures/new', to: 'signatures#sign'

  post '/form/finalize' => 'forms#finalize', :as => :finalize_form
  root to: "home#show"

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]
  resources :forms
  resources :form_types
  resources :roles
  resources :assignments
  resources :signatures

end

app/models/form_type.rb
class FormType < ApplicationRecord
  #attr_accessible :name, :fields_attributes

  has_many :fields, class_name: "FormField"
  accepts_nested_attributes_for :fields, allow_destroy: true
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :require_login
  def index
    @forms = Form.all
  end

  def show


    @form = Form.find(params[:id])
    @user = User.order('created_at DESC')
  end

  def new
    @form = Form.new(form_type_id: params[:form_type_id])

  end

  def edit
    @form = Form.find(params[:id])
    if !((@form.user_id == current_user.id) || (current_user.role? :admin))
      redirect_to root_path
    end
  end

  def create

    @form = Form.new(params[:form].permit!)
    if @form.save
      redirect_to @form, notice: 'Form was successfully created.'
    else
      render action: "new"
    end
    add_uid
    insert_signature
  end

  def insert_signature
    form = Form.last
    user = User.where(:email => "talmadge12@gmail.com").first
    if !form.grad
      Signature.create(:form_id => form.id, :user_id => user.id, :processed => FALSE)
    end
    if form.grad
    end
  end

  def add_uid

    form = Form.last
    Form.update(form.id, :user_id => current_user.id)
  end

  def update
    @form = Form.find(params[:id])
    if @form.update_attributes(params[:form].permit!)
      redirect_to @form, notice: 'Form was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @form = Form.find(params[:id])
    if !((@form.user_id == current_user.id) || (current_user.role? :admin))
      redirect_to root_path
    else
      @form.destroy
      redirect_to forms_url
    end
  end

  def finalize

    final = params[:finalize]
    final = final.to_i
    form_p = params[:form_id]
    form_id = form_p.to_i
    form = Form.where(:id => form_id).first
    form.update(finalized: 1)
    redirect_to root_path
  end


  private

  def form_params

    load_params = params.require(:form).permit(:name)
    load_params[:properties] = params[:form][:properties]
    load_params.permit!
  end


  def require_login
    unless !current_user.nil?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path # Halts request cycle.
    end
  end
end

app/helpers/forms_helper.rb
module FormsHelper
  def a_current_user
    user = User.where(:id => current_user.id)
    return user
  end
end

app/views/forms/_form.html.erb
<%= form_for @form do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>
      <ul>
      <% @form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :form_type_id %>

  <div class="field">
    <b><%= f.label :name, @form.form_type.name %></b><br>
    <%= f.label 'Student Name:' %>
    <%= f.text_field :name, placeholder: "Name"%><br>
    <br>
    <%= f.label 'Grad?(Leave unchecked if no)' %><br>
    <%= f.check_box :grad %>
  </div>

  <!-- OpenStruct creates a structure(naturally) that allows us to obtain form properties from the serialized json in FORM_TYPES -->
  <%= f.fields_for :properties, OpenStruct.new(@form.properties) do |builder| %>
    <% @form.form_type.fields.each do |field| %>
      <%= render "forms/fields/#{field.field_type}", field: field, f: builder %>
    <% end %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<div class="sidebarEdit">
  <h1>Editing form</h1>

  <%= render 'form' %>
</div>

app/views/forms/index.html.erb
  <div class="billboard">
    <h1 class="editHead">Forms</h1>

    <% if @forms.empty? %>
      <p><strong>No forms</strong></p>
    <% end %>


    <% @forms.each do |form| %>

      <!-- For each form, examine each form individually to check relations to
          signatures and the current user -->
      <% signaturePresent = false
         template_name = "<<MISSING TEMPLATE>>"%>
      <% if FormType.where(:id => form.form_type_id).present?
         form_type = FormType.where(:id => form.form_type_id).first
         template_name = form_type.name

       end%>
      <% if (Signature.where(:user_id => current_user.id).present?)%>
      <% signature = Signature.where(:user_id => current_user.id).first
         signaturePresent = true
         # allSignaturesForForm = Signature.where(:user_id => ).all%>
      <% end %>
      <div>
        <table>
          <tr>
            <%if ((form.user_id == current_user.id) || (current_user.role? :admin) || (signaturePresent))%>
            <td class="form_type"><%= form.name %> - <%= template_name %> </td>
            <td><%= link_to 'Show', form , class: 'avibuttons'%></td>
            <% if ((current_user.role? :admin) || (form.user_id == current_user.id)) %>
            <td><%= link_to 'Edit', edit_form_path(form), class: 'avibuttons' %></td><% end %>

            <td><% if ((current_user.role? :admin) || (form.user_id == current_user.id)) %>
              <%= link_to 'Delete', form,class: 'avibuttons', method: :delete, data: { confirm: 'Are you sure? This action is PERMANENT.' } %></td> <% end %>

          </tr>
        </table>
      <% end %>
      </div>

      <% end %>


    <%= form_tag new_form_path, method: :get do %>
      <%= select_tag :form_type_id, options_from_collection_for_select(FormType.all, :id, :name) %>
      <%= submit_tag "Select", name: nil %>
  </div>

<% end %>

app/views/forms/new.html.erb
<div class="sidebarEdit">
  <h1>New Form</h1>

  <%= render 'form' %>
</div>

<!-- <div class="dropsite">
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</div> -->

app/views/forms/show.html.erb
<% if (@form.finalized) %>
  <h3><div class="alart alert-info"> This form has been finalized. No more actions can be taken here. </div></h3>
<% end %>
<!-- This is where I'm dealing with all workflow frontend related to their relative controllers. -->
<% if (Signature.where(:form_id => @form.id).present?)%>
<% @signature = Signature.where(:user_id => current_user.id).first %>

<% #Defining variables for use in the form_tag
  form_id = @form.id
  @user = User.all
  @current_workflow = Signature.where(:user_id => current_user.id).first


  %>
<div class="dropsite">

  <% tepmlate_name= "<<NULL NAME DUE TO FORM TEMPLATE DELETION>>"
    if FormType.where(:id => @form.form_type_id).present?
      form= @form
      template= FormType.where(:id => form.form_type_id).first
      template_name= template.name
    end
    %>

  <h1><%= template_name%></h1><br>
  <b>Name:</b>
  <%= @form.name %>
  <% if @form.grad %>
    <%= "(Graduate)"%>
  <% end %>
  <% if !@form.grad %>
    <b><%= "(Undergraduate)"%></b>
  <% end %>
</p>
<% @form.properties.each do |name, value| %>
  <p>
    <b><%= name.humanize %>:</b>

    <!-- If the value is either 0 or 1, we're dealing with a checkbox. -->
    <% if  value == "0" %>
    <!-- TODO: Render an unchecked box. -->
      <%= image_tag("unchecked.png", :alt => "[Unchecked box image.]") %>
    <% elsif value == "1" %>
      <!-- TODO: Render a checked box -->
      <%= image_tag("checked.png", :alt => "[Checked box image.]") %>
    <% else %>
    <%= value %>
    <%end %>
  </p>
<% end %>
<% if Comment.where(:form_id => @form.id).present? %>
  <%@comments2 = Comment.where(:form_id => @form.id) %>
  <% @comments2.each do |c| %>
  <p>Signature: <%= c.name %></p>
  <% end %>
 <%end %>



</div>
    <div class="sidebarEdit">
      <h1>Form Details:</h1>
      <p>


      <p>
        <table>
          <tr>
            <td><%= link_to "Print", '#', class: "avibuttons",
            onclick: 'window.print();return false;' %>
            </td>
            <td><%if ((@form.user_id == current_user.id) || (current_user.role? :admin))%>
            <%= link_to 'Edit', edit_form_path(@form), class: 'avibuttons2' %>
             <% end %>
            </td>
            <td><%= link_to 'Back', forms_path , class: 'avibuttons2'%>
            </td>
          </tr>
        </table>
      </p>




        <% if (!(@signature.nil?) && (@signature.user_id == current_user.id && !@signature.processed)) %>

          <%= form_tag new_signature_path do %>
            <%if !(@form.finalized) %>
              <p>Signature:</p><%= text_field_tag "name", current_user.name %>
              <p> Comments(optional): </p>
              <%= text_area_tag "body", "", size: "30x5" %><br>

              <%= select_tag "user", options_from_collection_for_select(User.all, 'id', 'email') %>
              <%= hidden_field_tag("form_id", form_id) %>
              <%= hidden_field_tag("current_workflow", @current_workflow.id) %>
              <%= submit_tag "Send to Faculty Member"  %>
            <% end %>
          <% end %> <!-- End form tag -->

        <% end %> <!-- End block checking for nil -->
      <% end %>

      <% if (current_user.role? :admin) %>
        <% if !(@form.finalized) %>
          <%= form_tag finalize_form_path do %>
            <%= hidden_field_tag("form_id", @form.id) %>
            <%= hidden_field_tag("finalize", 1) %>
            <%= submit_tag "Finalize" %>
          <% end %>
        <% end %>
      <% end %>

    <% if ((Comment.where(:form_id => @form.id).any?) && ((@signature.user_id == current_user.id || (current_user.role? :admin))))  %>
       <p> Comments: </p>
        <%@comments = Comment.where(:form_id => @form.id) %>
        <% @comments.each do |c| %>
        <div class="panel panel-default">
          <div class="panel-body">
            <%= "[" + c.name + "]:"%>
            <%= c.body %>
          </div>
        </div>
    </div>
    <% end %>
<% end %>